[package]
name = "rust-sqlite-connect"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1.13.0", features = ["attributes"] }
futures = "0.3.31"
sqlx = { version = "0.8.2", features = ["runtime-async-std-native-tls", "sqlite"] }
